apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://host.docker.internal:64972
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: jenkins
  name: minikube
current-context: minikube
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhDWlcwbzNtNWFMelhQZ244bDRzSzREaDIta0FrNXllLU92dWdMRTJQRzQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzYxNjQ1NDk3LCJpYXQiOjE3NjE2NDE4OTcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODcxM2U1MzMtYzRhZC00MTYyLWFmMmMtY2RhNGJiYzAwN2Y2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2EiLCJ1aWQiOiJmZDQ5ZTg1ZS0yMDNlLTRjNGItYjRmNS1jNDc0ZWE3ODBkOWEifX0sIm5iZiI6MTc2MTY0MTg5Nywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6amVua2lucy1zYSJ9.BlfWTwsgsXc0r2sRp7K3I_mgcC_gsW8XBV-fGXyJlPQ2Cu6hsl7_JwmB2ToLA9uVtGd-I8y_gcHcwX9w64B2ROHczwqu9QgVOODlGkOqAdMGfpB9lx4ZicIWWO4Ssv3amhaS2Va0dnZSS9SOjUe1C9xFLc5u2t-RwGJAbbE0E5gb-h71rMPq-_bWZALsMeS4tcd1NRksXIWcJMUKSNCA6PFqu4v3jBct-6NKPdSI6-iUueFX0AKxMeTR3a5Xk_n3bEt-jCCNYPt2HUNgdVyWvuMepoXZuD2tJ8LSdEBBQ2L6SILNogyb37lOnyi_6XIIJPk5CqG2-KB3_sxDI_97Lg
