# values.yaml — Chart Helm pour ton app Node.js

replicaCount: 1

image:
  repository: achrefmessai/dockerapp1
  tag: "latest"              # Jenkins mettra à jour dynamiquement ce tag
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}
  # Exemple :
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 5

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  automount: false
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
